# Base directories
scripts: "analysis/scripts"
output_dir: "analysis/outputs"
input_data: "analysis/input_data"

# Output directories
dl_output_dir: "analysis/outputs/download_data"
gene_bed_dir: "analysis/outputs/download_data/gene_beds"
ref_genome_dir: "analysis/outputs/download_data/ref_genomes"
varcall_dir: "analysis/outputs/call_variants"
jointgeno_dir: "analysis/outputs/joint_genotyping"

# Containers
container_gramtools: "container/built/singu.sif"
container_minos: "container/built/minospb.sif"

# Sample tsvs
pf6_tsv: "analysis/input_data/sample_lists/pf6/pf6_samples.tsv"
pf6_validation_tsv: "analysis/input_data/sample_lists/pf6/nesting_paper_samples_in_pf6.tsv"
pvgv_tsv: "analysis/input_data/sample_lists/pvgv/pvgv_samples.tsv"
pvgv_validation_tsv: "analysis/input_data/sample_lists/pvgv/pvgv_validation_samples.tsv"
pacb_ilmn_pf_tsv: "analysis/input_data/sample_lists/pacb_ilmn_pf/pacb_ilmn_pf.tsv"
