# Base directories
scripts: "analysis/scripts"
common_scripts: "analysis/scripts/common_utils"
output_dir: "analysis/outputs"
input_data: "analysis/input_data"

# Output directories
dl_output_dir: "analysis/outputs/download_data"
assemblies_dir: "analysis/outputs/download_data/pacb_ilmn_pf/assemblies"
gene_bed_dir: "analysis/outputs/download_data/gene_beds"
ref_genome_dir: "analysis/outputs/download_data/ref_genomes"
varcall_dir: "analysis/outputs/call_variants"
jointgeno_dir: "analysis/outputs/joint_genotyping"

# Containers
container_gramtools: "container/built/singu.sif"
container_minos: "container/built/minospb.sif"

# Sample tsvs
pf6_tsv: "analysis/input_data/sample_lists/pf6/pf6_samples.tsv"
pf6_validation_tsv: "analysis/input_data/sample_lists/pf6/pf6_analysis_set_fws95_500.tsv"
pvgv_tsv: "analysis/input_data/sample_lists/pvgv/pvgv_samples.tsv"
pvgv_validation_tsv: "analysis/input_data/sample_lists/pvgv/pvgv_validation_samples.tsv"
pacb_ilmn_pf_tsv: "analysis/input_data/sample_lists/pacb_ilmn_pf/pacb_ilmn_pf.tsv"
clone_tree_tsv: "analysis/input_data/sample_lists/generational_samples/clone_trees.tsv"
crosses_tsv: "analysis/input_data/sample_lists/generational_samples/crosses.tsv"
laverania_illumina_tsv: "analysis/input_data/sample_lists/laverania_illumina/laverania_illumina.tsv"

## Bed files
pf3d7_2018_11_core_regions: "analysis/input_data/pf3d7_2018_11_regions_in_core.bed"

## Variant calling params
gapfiller_insert_size_mean: 600
gapfiller_insert_size_stdv: 1000

## Mapping-to-induced-ref evaluation
eval_bed_files:
    pf6_26_genes: "analysis/input_data/eval_varcalls/pf6_26_genes_and_DBL.bed"
