# Base directories
scripts: "analysis/scripts/plasmo_paralogs"
plotting_scripts: "analysis/scripts/plasmo_paralogs/plotting"
output_dir: "analysis/outputs"
input_data: "analysis/input_data"

container_gramtools: "plasmo_surfants/reproducibility/container/built/singu.sif"

paralog_abbrevs: ["DBs","AMA1","MSP3","MSP6","EBA175","MSP2","MSP1"]
paralog_names:
    DBs: ["DBLMSP", "DBLMSP2"]

sqlite_table_names: ["domain_coordinates","pf6_metadata","seq_colour_schemes"]
sqlite_fnames:
    # DBL domain
    domain_coordinates: "analysis/input_data/domain_coordinates.tsv"
    pf6_metadata: "plasmo_surfants/analysis/input_data/sample_lists/pf6/pf6_samples.tsv"
    # Sequence colour schemes for visualisation
    seq_colour_schemes: "analysis/input_data/sequence_colour_schemes.tsv"
    ir_stats: "analysis/input_data/analysed_sequences/ir_stats_all.tsv"

input_tsvs:
    ir_stats_fold_covs: "analysis/input_data/analysed_sequences/ir_stats_fold_coverages.tsv"
    laverania_assemblies: "analysis/input_data/laverania_assemblies.tsv"
DBs_single_snp_solved_seqs: "analysis/input_data/analysed_sequences/DBs_single_snp_solved_seqs.fa"

domain_extra_amino_acid_window_size: 10
