scripts: "analysis/scripts"
output_dir: "analysis/outputs"
dl_output_dir: "analysis/outputs/download_data"
input_data: "analysis/input_data"
gram_builds_dir: "analysis/outputs/gram_builds"
container_gramtools: "container/built/singu.sif"
container_minos: "container/built/minospb.sif"
