ref_genomes:
    ftp_root: "ftp://ftp.sanger.ac.uk/pub/project/pathogens/gff3/2018-11/"
    genomes: ["PvivaxP01", "Pfalciparum"]
    extensions: [".genome.fasta.gz", ".genome.fasta.gz.fai", ".gff3.gz"]

pacb_pf_ftp: "ftp://ftp.sanger.ac.uk/pub/project/pathogens/Plasmodium/falciparum/PF3K/ReferenceGenomes_Version1/GENOMES/*.fasta.gz"
vcf:
    pf6_url: "https://ngs.sanger.ac.uk/production/malaria/pfcommunityproject/Pf6/Pf_6_vcf/"
    pf6_fname_template: "Pf_60_public_Pf3D7_{chrom}_v3.final.vcf.gz"

gene_list_dir: "analysis/input_data/gene_lists"
pf7_vcf: "analysis/input_data/pf7/Pf3D7_v3_pf7_otto_samples_renamed.vcf.gz"
pf6_gene_list_files: ["pf6_26_genes"]
pvivax_gene_list_files: ["pvivax_7_genes"]

subsampling_maxcov: 60
